### ISSUE TITLE
Command to install vale on Linux is incorrect

### ISSUE THREAD

**Issue by Namyalg** [errata-ai/docs#9]
The [command](https://github.com/errata-ai/docs/blob/main/website/docs/vale/install.mdx) to install vale on Linux is given as 
`brew install vale`

**Comment by jdkato** [comment]
See https://docs.brew.sh/Homebrew-on-Linux.

Of course, this is merely an option and you’re free to install from a GitHub release or another package manager.

**Comment by Namyalg** [comment]
Okay, thank you
